# @package _global_
name: &name LinearGaussian
log_level: INFO

sim:
  _target_: src.sim.linear_gaussian_sim.LinearGaussianSimulation
  env:
    _target_: src.steppers.env_stepper.EnvStepper
    inner_env:
      _target_: ${get_env:${sim._target_}}
      prior_policy: &prior
        _target_: src.policies.linear_gaussian_policies.GaussianPolicy
        dim: &dim 1
        A: &A [[0.8990]]
        Q: &Q [[1.2858]]
      num_particles: &num_particles 10
      dim: *dim
      likelihood:
        _target_: src.likelihoods.likelihoods.LinearGaussianLikelihood
        C: &C [[0.6941]]
        R: &R [[0.3740]]
      time_limit: &time_limit 500
      ess_threshold: 0.9
      resampler:
        _target_: src.resamplers.NoResampler
      train: False
    recorder:
      _target_: src.steppers.recorders.recorder.Recorder
      name: *name
      num_particles: *num_particles
    steppers:
      - visualizer:
        _target_: src.steppers.visualizers.visualizer.Visualizer
        name: *name
        time_limit: *time_limit
  proposal_policy:
    _target_: src.policies.linear_gaussian_policies.OptimalFilteringPolicy
    A: *A
    C: *C
    Q: *Q
    R: *R
