# @package _global_
name: ""
log_level: INFO

sim:
  _target_: src.sim.sim.Simulation
  env:
    _target_: src.env.RecorderEnv
    num_particles: 1500
    start_x: 0
    start_y: 0.5
    goal_x: 1
    goal_y: 0.5
    max_diff: 0.05
  policy:
    _target_: src.policy.Policy
    dim: 2
  resampler:
    _target_: src.sim.resamplers.MultinomialResampler
  num_rounds: 5

visualizer:
  _target_: src.visualizer.Visualizer
  num_rounds: 5
  env: ${sim.env}
  policy: ${sim.policy}
